version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mwc_backend
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "443:443"  # For HTTPS
    environment:
      # Basic configuration
      - PORT=8081

      # AWS RDS PostgreSQL configuration
      - DATABASE_URL=postgres://postgres:yourpassword@your-rds-instance.rds.amazonaws.com:5432/mwcdb?sslmode=require

      # Amazon MQ configuration
      - RABBITMQ_URL=amqps://username:password@your-amazonmq-broker.mq.us-east-1.amazonaws.com:5671/
      - RABBITMQ_USE_TLS=true
      - RABBITMQ_CERT_PATH=/app/certs/rabbitmq

      # HTTPS configuration for WSS
      - SSL_ENABLED=true
      - SSL_CERT_FILE=/app/certs/ssl/certificate.pem
      - SSL_KEY_FILE=/app/certs/ssl/private-key.pem

      # WebSocket configuration
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_PATH=/ws

      # Other configuration
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=user
      - SMTP_PASSWORD=password
      - EMAIL_FROM=no-reply@example.com
      - JWT_SECRET=your_jwt_secret_key
      - STRIPE_SECRET_KEY=your_stripe_secret_key
      - STRIPE_WEBHOOK_SECRET=your_stripe_webhook_secret
      - STRIPE_MONTHLY_PRICE_ID=price_monthly
      - STRIPE_ANNUAL_PRICE_ID=price_annual
      - DEFAULT_LANGUAGE=en
      - SUPPORTED_LANGUAGES=en,es,fr
      - DEFAULT_ADMIN_EMAIL=admin@example.com
      - DEFAULT_ADMIN_PASSWORD=Admin123!
      - DEFAULT_ADMIN_FIRST_NAME=Admin
      - DEFAULT_ADMIN_LAST_NAME=User
    volumes:
      # Mount SSL certificates
      - ./certs/ssl:/app/certs/ssl
      # Mount RabbitMQ certificates
      - ./certs/rabbitmq:/app/certs/rabbitmq

